<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fluid-HTN">
      <HintPath>../../../fluid-hierarchical-task-network/Fluid-HTN/bin/Debug/Fluid-HTN.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Fluid-HTN-Ext\Fluid-HTN-Ext.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="domain.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
